#### The use of IQ as an indicator of harm

Community members in Pittsburgh are entirely correct to be concerned about IQ, because IQ scores have been badly misused to support racism. But there are also valid and responsible reasons to understand this data.

##### Is IQ data reliable?

The IQ measure has been found to be a very reliable indicator of cognitive impairment in groups of children exposed to environmental toxins.

Decades ago, carefully controlled IQ testing helped demonstrate that lead poisoning damages children's brains, resulting in measurable losses in cognitive function and lowered IQ. That research showed that the effects of lead exposure occur in children of **every race and at every income level.**

##### Why was IQ used in this study?

The goal in presenting the IQ data was not to label any group of children as less intelligent, but to show that air pollution is damaging the brains of children across Southwestern Pennsylvania.

The findings show that those with the highest air pollution exposure experience the greatest cognitive harm, regardless of race or background, underscoring the need to reduce air pollution levels in Pittsburgh.

The central issue here is not misuse of the IQ test, but rather that children in southwestern PA are being damaged by polluters who use the air as a low-cost dumping ground for their toxic, unwanted waste. This unconscionable, irresponsible and immoral behavior by polluters needs to end. Air pollution in Pittsburgh damages the health of all Pennsylvanians of all ages and of every race — this study hopes to highlight the need to reduce the harms.

##### Is IQ culturally biased?

When IQ is used to assess the intellectual capacity of an <u>individual</u> child, it is <u>highly</u> influenced by cultural factors.

Children who grow up in higher-income, English-speaking households often score higher on IQ tests than minority children from low-wealth households or non-English-speaking backgrounds. This differential is not due to differences in the children's cognitive functioning, but rather to differences in their backgrounds.

Historically, IQ scores have been misused to wrongly characterize Black and Brown children as less intelligent than White children. For these reasons, use of the IQ test is inappropriate for a diagnosis of cognitive capacity in an <u>individual</u> child.

##### How is this study different from past, culturally insensitive studies?

This study did not look at the IQ tests of *individual* children, but rather used the data from *entire census tracts* to show that air pollution is damaging the brains of children across Southwestern Pennsylvania.

##### How can this data influence change?

Evidence of IQ loss was a powerful motivator in the U.S. EPA's decision to remove lead from gasoline and paint. Those actions resulted in an approximate 95% reduction in blood lead levels among American children and significant improvements in cognitive outcomes nationwide.

Similarly, research demonstrating IQ loss in children exposed to harmful pesticides contributed to restrictions on those toxic chemicals.
